spring:
  datasource:
    url: jdbc:mysql://localhost:3306/product?createDatabaseIfNotExist=true
    username: root
    password:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57InnoDBDialect
        globally_quoted_identifiers: true
    show-sql: true
    hibernate:
      ddl-auto: update
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
  data:
    rest:
      base-path: /api/v1/
  main:
    allow-circular-references: true
server:
  port: 8081
